### ISSUE TITLE
Package version

### ISSUE THREAD

**Issue by Shuunen** [Shuunen/vue-image-compare#10]
Should it be 0.0.1 ?

I would say it's too late because I published versions 0.7.0 and above and NPM might consider the nexts releases as prior to these, what do you think @ctf0 ?

**Comment by ctf0** [comment]
u r correct, np then, btw i think as we've already published the package, the prs on the original forks are kinda useless.

**Comment by Shuunen** [comment]
can't we use some of them to improve this lib ?

**Comment by ctf0** [comment]
😄 👍
