### ISSUE TITLE
Enhance demo options form styling

### ISSUE THREAD

**Issue by Shuunen** [Shuunen/vue-image-compare#11]

**Comment by ctf0** [comment]
actually if you want we can move the whole demo to codebox instead of maintaining the branch which will add an extra load for anyone wants to fork the project

**Comment by ctf0** [comment]
here u go https://codesandbox.io/s/j7wyj555o3

**Comment by Shuunen** [comment]
fixed by 8702a2188387f1f202153e2358cf3430b4f1b0c2

**Comment by ctf0** [comment]
add `.vscode` to gitignore
