### ISSUE TITLE
Before and After images do not update when props change

### ISSUE THREAD

**Issue by jlariza** [Shuunen/vue-image-compare#12]
Good day,

I need to be able to change the images dynamically. However, if I change `:before` and `:after` props, it does not re render the component. Checking the code, I notice that you have this on the data object 
```
mutableBefore: this.before,
mutableAfter: this.after,
```
So, you are not using the props directly but a variable with its value that is set when the component is created. This means that the value will be constant even if the props are modified. Is it a way to avoid this behaviour?

Thank you,

**Comment by Shuunen** [comment]
Hi @jlariza I did not worked on this part so feel free to upgrade it 👍 

Let's discuss on your PR #13
